# Generated by Django 5.0.2 on 2024-02-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_ref_no",
                    models.UUIDField(
                        unique=True, verbose_name="Client reference number"
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inactive", "INACTIVE"),
                            ("paid_in_full", "PAID IN FULL"),
                            ("in_collection", "IN COLLECTION"),
                        ],
                        default="inactive",
                        max_length=25,
                    ),
                ),
                ("consumer_name", models.CharField(max_length=100)),
                ("consumer_address", models.TextField()),
                ("ssn", models.CharField(max_length=20)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Customer Balance",
                "verbose_name_plural": "Customer Balances",
            },
        ),
    ]
