# Generated by Django 5.0.2 on 2024-02-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_ref_no",
                    models.UUIDField(
                        unique=True, verbose_name="Client reference number"
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INACTIVE", "INACTIVE"),
                            ("PAID_IN_FULL", "PAID IN FULL"),
                            ("IN_COLLECTION", "IN COLLECTION"),
                        ],
                        default="INACTIVE",
                        max_length=25,
                    ),
                ),
                ("consumer_name", models.CharField(max_length=100)),
                ("consumer_address", models.TextField()),
                ("ssn", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Customer Balance",
                "verbose_name_plural": "Customer Balances",
            },
        ),
    ]
